### ISSUE TITLE
Remote SDR v5 not starting after apt upgrade on Raspberry PI

### ISSUE THREAD

**Issue by brkaucher** [F1ATB/Remote-SDR#39]
Hello,

First thank you very much for your great work!
I've just started playing arround with it.

After a "sudo apt upgrade" Remote SDR v5" is not starting anymore.
I've tried to start it manually and get these error:

pi@remsdr-rpi4:/remsdr $ node Radio_Server.js
node:internal/fs/utils:347
    throw err;
    ^

Error: EINVAL: invalid argument, write
    at Object.writeSync (node:fs:920:3)
    at Object.writeFileSync (node:fs:2208:26)
    at exportGpio (/remsdr/node_modules/onoff/onoff.js:18:8)
    at new Gpio (/remsdr/node_modules/onoff/onoff.js:172:36)
    at Object.<anonymous> (/remsdr/remsdr_modules/CPU.js:27:15)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19) {
  errno: -22,
  syscall: 'write',
  code: 'EINVAL'
}

Within CPU.js is a distinction between Raspberry and Orange PI with help from the lscpu command. 

var info_cpu = cp.execSync("lscpu").toString();
// console.log('info_cpu: ' + info_cpu);
if (info_cpu.indexOf("armv7l") > 0) {
    Model = "Raspberry PI4";
    CPUshort = "RPI4";
    GPIO_Fan = "4"; // Pin 7 on Raspberry
    GPIO_Oscil = "7";
}
if (info_cpu.indexOf("aarch64") > 0) {
    Model = "Orange PI Zero One Plus";
    CPUshort = "opi1p";
    if (info_cpu.indexOf("1512.0") > 0) {
        Model = "Orange PI Zero 2";
        CPUshort = "opiz2";
        GPIO_Oscil = "74";
    }
}

After upgrading the RasPi it runs with 64 Bit and returns now  'Architecture:  aarch64" too.

As workaround I've modified CPU.js by setting the variables for the Raspberry Pi without the if statement and commented the Orange Pi part out. Now at least Radio_Server.js is starting again and it seams to work. Don´t know if there will maybe other problems with this modifikation.

Regards Bernd (DF1PZ)

**Comment by brkaucher** [comment]
within #36 this problem is already mentioned
